### PR TITLE
Refactor image handling and add support for saving images as base64 s…

### PR DESCRIPTION
**Pull request by NoamMuallem**
As mentioned in the  #8, to really use notion as a CMS, one needs to save the encoded images to the data-store.json to get all the benefits of a statically generated website.

### CODE REVIEW

**Comment by NoamMuallem** [comment]
@NotWoods let me know if you have any preference as to where to place the new function, I am currently struggling with the typing a little bit...

**Comment by NotWoods** [comment]
Thank you for the PR! Reviews are going to be a bit slow right now as I'm on bereavement leave but I wanted to give some early feedback.

I like the idea of being able to store the images, but I'm interested in using [Astro's image APIs](https://docs.astro.build/en/reference/modules/astro-assets/) rather than just converting to base64. Base64 is pretty inefficient and will hurt the end-user experience as it will pages take much longer to download.

[Astro MDX uses a rehype parser](https://github.com/withastro/astro/blob/main/packages/integrations/mdx/src/rehype-images-to-component.ts) to convert `` tags into Astro Image components and I'd like to explore something similar here. It might even be possible to just import the existing rehype parser.

**Comment by NoamMuallem** [comment]
cool idea, like using the getImage function and store the optimized image?
About the parser, and the astro Image components, for me (and I think, for the package), it is out of scope because it effects the rendering of the stored content, and not the stored content itself...

**Comment by NotWoods** [comment]
Yeah, I'm thinking of the `getImage` function. Astro loaders do handle rendering so I don't feel that it's out of scope but you might be able to get the same effect working with Notion blocks.

**Comment by NotWoods** [comment]
I used the code here to create #14 using the Astro `getImage` function. If this doesn't work well long term we can revisit base64 URLs as an alternate caching solution :)

**Pull request closed without merging**
